### ISSUE TITLE
Fails to build against glib-2.68.

### ISSUE THREAD

**Issue by zarniwhoop73** [sergiomb2/ufraw#10]
In glib-2.68 <type_traits> was included from gatomic.h, causing a large number of 'error: template with C linkage' reports from uf_glib.h.

I've fixed this for my own (limited) build, but I do not use all the options (not libjasper, FITS, lensfun) so I'm not sure if this is a full fix, otherwise I would create a merge request. For some reason the preview decides the removed lines are markup and makes them bold, even if I put this in `code` tags. Can't see any way to attach a diff, only images.

```
diff -Naur a/uf_glib.h b/uf_glib.h
--- a/uf_glib.h 2020-11-13 10:47:14.000000000 +0000
+++ b/uf_glib.h 2021-04-11 18:50:54.704015730 +0100
@@ -13,13 +13,13 @@
 #ifndef _UF_GLIB_H
 #define _UF_GLIB_H
 
+#include <glib.h>
+#include <glib/gstdio.h>
+
 #ifdef __cplusplus
 extern "C" {
 #endif
 
-#include <glib.h>
-#include <glib/gstdio.h>
-
 // g_win32_locale_filename_from_utf8 is needed only on win32
 #ifdef _WIN32
 #define uf_win32_locale_filename_from_utf8(__some_string__) \
```

**Comment by sergiomb2** [comment]
Thank you
