### ISSUE TITLE
Removal of GtkImageView headers breaks the build

### ISSUE THREAD

**Issue by mardy** [sergiomb2/ufraw#14]
The last commit (2aaabfa4ac19ef74f3abdafc683f62182d577480) breaks the build, because it removes the GtkImageView as a dependency while it's still being used in ufraw_preview.c

The commit message seems to imply that this widget is present in Gtk 2.10, but that does not appear to be the case.

**Comment by sergiomb2** [comment]
yes, I overlooked

**Comment by mardy** [comment]
Thanks!
