### ISSUE TITLE
ufraw crash

### ISSUE THREAD

**Issue by rosorio** [sergiomb2/ufraw#2]
Someone reports me an issue with ufraw, who makes the application crash.

All the details about how to reproduce and a sample image are available in our
bug tracker https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226544

Feel free to contact me or the bug report author if you have questions

All the best
- rodrigo

**Comment by sergiomb2** [comment]
github project is not the official project , but have the latest code .

I wrote here [1] what I had done but author doesn't reply , also
meanwhile sourceforge close cvs repos , so project as is can't have
more updates . 

Also like DCRaw (UFRaw-0.22 is based on DCRaw v 9.26.) the project
seems abandoned but now we have libraw [2] (maybe that is the reason I
don't know) 

I just add all tags with `git push --tags origin` cool. 

if you have pull requests they are welcome , but I don't know if I will
spend more time with this project TBH . 

Best regards,

[1]
https://sourceforge.net/p/ufraw/mailman/ufraw-devel/?viewmonth=201610


[2]
https://github.com/LibRaw/LibRaw

**Comment by GaryAitken** [comment]
Sérgio,

Neither Rosorio nor I have push access to the repository.  So either
you will need to pull/merge the changes, or else you could grant
push access to either Rosorio or me or both of us so we can integrate
them.

Thanks,

Gary

**Comment by sergiomb2** [comment]
Gary , I'm not the owner of the project , neither pretended to be , and that is why I don't have here fedora patches ... 

@rosorio I did this patch [1] after one report that ufraw crash on exit , don't know if it helps 

[1] https://src.fedoraproject.org/rpms/ufraw/blob/master/f/ufraw-0.22-lf-destroy.patch 

I will try merge your patches , but why you (Gary) don't fork this repo ?

**Comment by sergiomb2** [comment]
> Feel free to contact me or the bug report author if you have questions

After read your bug report is not related with my patch , I'm more focused in migrate all to libRaw 
anyway thanks for the report, I mean rawstudio which use ufraw and is the reason of this repo

**Comment by GaryAitken** [comment]
Thanks, Sérgio!

> Feel free to contact me or the bug report author if you have 
> questions
> 
> After read you bug report is not related with my patch , I'm more 
> focused in migrate all to libRaw anyway thanks for the report

Are you saying you are working on migrating ufraw to libraw?  That is
one of the things I was considering working on after I get caught up.
If you are working on that I will focus on something else, as you
are probably better equipped to do it than I am.

**Comment by sergiomb2** [comment]
I'd like migrate rawstudio ufraw plugin to libraw , but I'm not working on that . libraw have  dcraw and ufraw is based on dcraw .
