### ISSUE TITLE
ufraw doesn't find anymore final gimp 2.10.0

### ISSUE THREAD

**Issue by david-geiger** [sergiomb2/ufraw#4]
Hi,

I tried on Mageia Cauldron to compile ufraw 0.22 against final gimp 2.10.0 but it fails to find it:

> checking for gimpui-2.0 >= 2.2.0... no
configure: build GIMP plug-in: no

**Comment by sergiomb2** [comment]
What you suggest fix here : 
https://github.com/sergiomb2/ufraw/blob/master/configure.ac#L112-L121 ?

**Comment by david-geiger** [comment]
Ah I see someone has fixed gimp 2.10.0 on mageia and now ufraw is again able to detect gimp and build fine:

http://svnweb.mageia.org/packages/cauldron/gimp/current/SOURCES/gimp-2.10.0-gegl04.patch?view=markup&pathrev=1229395

Sorry for this unneeded bug report :(
