### ISSUE TITLE
Failing Build Against exiv2 master

### ISSUE THREAD

**Issue by jbylund** [sergiomb2/ufraw#6]
Needed to do this to get it to build against newest exiv2 (I'm deep in dependency hell, so apologies for not formatting better).
```diff
diff --git a/ufraw_exiv2.cc b/ufraw_exiv2.cc
index 873bacc..62c7d92 100644
--- a/ufraw_exiv2.cc
+++ b/ufraw_exiv2.cc
@@ -50,7 +50,7 @@ extern "C" int ufraw_exif_read_input(ufraw_data *uf)
         uf->inputExifBuf = NULL;
         uf->inputExifBufLen = 0;
 
-        Exiv2::Image::AutoPtr image;
+        Exiv2::Image::UniquePtr image;
         if (uf->unzippedBuf != NULL) {
             image = Exiv2::ImageFactory::open(
                         (const Exiv2::byte*)uf->unzippedBuf, uf->unzippedBufLen);
@@ -347,7 +347,7 @@ extern "C" int ufraw_exif_write(ufraw_data *uf)
 
         char *filename =
             uf_win32_locale_filename_from_utf8(uf->conf->outputFilename);
-        Exiv2::Image::AutoPtr image = Exiv2::ImageFactory::open(filename);
+        Exiv2::Image::UniquePtr image = Exiv2::ImageFactory::open(filename);
         uf_win32_locale_filename_free(filename);
         assert(image.get() != 0);
```

**Comment by sergiomb2** [comment]
what version is for you the newest exiv2 ? 0.27.2 or newer ?

**Comment by jbylund** [comment]
I appear to be on https://github.com/Exiv2/exiv2/commit/8c91d6bd196152918cf23141883c52e1f6dfd65d (not implying that's the first commit where this happened)

**Comment by prusnak** [comment]
It seems that Exiv2 0.27.3 (latest stable) does not contain `Exiv2::Image::UniquePtr`; see https://www.exiv2.org/doc/classExiv2_1_1Image.html ; so I am not sure how the patch can fix any build failure.

**Comment by sergiomb2** [comment]
https://github.com/sergiomb2/ufraw/blob/master/ufraw_exiv2.cc#L53 still using  Exiv2::Image::AutoPtr , this patch was not merge yet ...

**Comment by sergiomb2** [comment]
Closing, because seems all that I can do, was done . Please open a new issue or reopen this one, if not.

Thank you.
